feat(search): make search field sticky on scroll
hankxdev/one-click-extensions-manager pull request #151
Opened 2024-08-13 18:02 UTC by Anujjoshi3105

Fixes #147 
The search field remains visible at the top of the viewport when scrolling.
![image](https://github.com/user-attachments/assets/5cfd7f28-768f-4450-b774-d4d8bb4a8bb1)

2024-08-13 18:17 UTC, fregante requested changes
Thanks for the PR! However what I had asked is exactly what's needed, not `position: absolute`

```css
.header {
    position: sticky;
    top: 10px;
    background: gray;
    outline: solid 10px gray;
	z-index: 100
}
```

Just the values need to be adjusted, for example to use `var()` for the margin and the color.


![scroll](https://github.com/user-attachments/assets/359dd012-9049-493f-9868-784dfaf67eba)

2024-08-13 19:04 UTC, fregante approved these changes

2024-08-13 19:04 UTC, fregante commented on source/style.css
> +	outline: solid var(--margin) #2b2c2c;
I think this fixes support for light mode too. Can you verify? Make send a new gif

```suggestion
	outline: solid var(--margin) light-dark(#fff, #292a2d);
```

2024-08-14 04:05 UTC, Anujjoshi3105 commented
Ligth and dark mode working 
![light](https://github.com/user-attachments/assets/51627310-220e-46bd-a582-7c4dd40e0e51)

2024-08-14 04:13 UTC, merged

2024-08-14 04:13 UTC, fregante commented
Thank you!